### ISSUE TITLE
“登录信息验证失败，请重新登录”

### ISSUE THREAD

**Issue by ainexur** [sw-ashai/ashai_ninja#1]
复现步骤：
1.单击注册
2.输入用户名、Cookie
3.单击确定（此时提示注册成功，自动跳转到登录页）
4.输入注册的用户名，单击登录
5.页面先跳转到用户页后即刻又跳转回登录页，上方提示“登录信息验证失败，请重新登录”

**Comment by svenshi** [comment]
尝试清空对应网站在浏览器中的localstorage，清空后尝试重新登陆。

**Comment by zhk55236** [comment]
您好，清空后不行，我换了个新手机登也是提示这个

**Comment by svenshi** [comment]
@zhk55236  服务器是你部署的吗 把青龙容器里你的环境变量删掉试试，我有空会排查一下

**Comment by zhk55236** [comment]
> @zhk55236 服务器是你部署的吗 把青龙容器里你的环境变量删掉试试，我有空会排查一下

是的，我自己的服务器。我按您的要求将环境变量删了，登陆就显示未注册用户

**Comment by svenshi** [comment]
@zhk55236 重新注册应该可以解决

**Comment by zhk55236** [comment]
@SvenShi 还是不行，一样的提示::>_<::

**Comment by svenshi** [comment]
> @SvenShi 还是不行，一样的提示::>_<::

等我有时间排查一下把

**Comment by zhk55236** [comment]
好的，感谢

**Comment by svenshi** [comment]
> 好的，感谢

我刚才看了一下代码，有以下几种情况会导致登录时弹出"登录信息验证失败，请重新登录"：
- 青龙容器中没有对应用户名的环境变量
- `.env`文件中的配置项`USERNAME_SALT`配置的盐的字符长度不是8的倍数，导致加密用户名后无法解密用户名
检查以上两个问题后，请回复结果

**Comment by zhk55236** [comment]
> > 好的，感谢
> 
> 我刚才看了一下代码，有以下几种情况会导致登录时弹出"登录信息验证失败，请重新登录"：
> 
> * 青龙容器中没有对应用户名的环境变量
> * `.env`文件中的配置项`USERNAME_SALT`配置的盐的字符长度不是8的倍数，导致加密用户名后无法解密用户名
>   检查以上两个问题后，请回复结果

您好，问题解决了。
我分析了下原因有两个：
一、网页管理员账户修改的密钥与本地.env文件中的密钥不一致；
二、本地.env密钥修改后未pm2 start，导致密钥未真正生效。

**Comment by svenshi** [comment]
> 

多谢，密钥修改不会实时生效的问题已经修复 44228bd77c63b2772ab20bf323d38d74bec03ee2

**Comment by zhk55236** [comment]
> 

您好，刚更新最新ninja，可以正常登陆普通用户，但登陆admin确显示您无权操作。查看本地.env文件ALLOW_ADMIN=true。

更新代码前可以登陆，更新后出现这个问题，清空浏览器问题仍然存在，不知道什么原因。
