### ISSUE TITLE
管理员账号登录时提示“您无权操作”

### ISSUE THREAD

**Issue by svenshi** [sw-ashai/ashai_ninja#4]
您好，刚更新最新ninja，可以正常登陆普通用户，但登陆admin确显示您无权操作。查看本地.env文件ALLOW_ADMIN=true。

更新代码前可以登陆，更新后出现这个问题，清空浏览器问题仍然存在，不知道什么原因。

_Originally posted by @zhk55236 in https://github.com/SvenShi/sven_ninja/issues/1#issuecomment-1441238240_

**Comment by svenshi** [comment]
@zhk55236 是不是最新的代码，我刚在12点多的时候更新了代码

**Comment by zhk55236** [comment]
是最新代码，刚刚又重新git，问题依然在

**Comment by SvenShi** [comment]
> 

我晚上看一下

**Comment by svenshi** [comment]
> 是最新代码，刚刚又重新git，问题依然在

我晚上看一下

**Comment by FW27623** [comment]
确实是这样，我也提示无权操作，卡在管理界面一直循环转圈
![image](https://user-images.githubusercontent.com/59783568/220843067-246208ad-d64a-48c2-b64b-a9a12c2ca0f8.png)

**Comment by svenshi** [comment]
> 确实是这样，我也提示无权操作，卡在管理界面一直循环转圈 ![image](https://user-images.githubusercontent.com/59783568/220843067-246208ad-d64a-48c2-b64b-a9a12c2ca0f8.png)

等我晚上看一下，昨天重构了一下验证管理员的逻辑。白天上班没空

**Comment by FW27623** [comment]
> 

好的，麻烦了，不过主要更新ck还是能用的，也不是很着急

**Comment by svenshi** [comment]
此bug已在 c013c64a871e827d3e513a4fee5c30627bd68060 修复，感谢两位反馈！

**Comment by FW27623** [comment]
> 此bug已在 [c013c64](https://github.com/SvenShi/sven_ninja/commit/c013c64a871e827d3e513a4fee5c30627bd68060) 修复，感谢两位反馈！

更新后已修复，谢谢作者😁
