### ISSUE TITLE
谢谢作者，成功部署，请问什么时候支持WSKEY呀

### ISSUE THREAD

**Issue by wejudging** [sw-ashai/ashai_ninja#5]
谢谢作者，成功部署，请问什么时候支持WSKEY呀

**Comment by svenshi** [comment]
不加了 没有多余精力维护了

**Comment by wejudging** [comment]
我刚刚自己在手机端上抓包，但是并没有看到WSKEY选项，是京东那边移除了吗，还是有什么改动，还是我刚刚在app登录的账号不产生wskey，要等一段时间呀
